version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
    env_file:
      - db.env

  redis:
    image: redis:alpine
    restart: always

  app:
#    image: nextcloud
    build: ./app
    restart: always
    ports:
      - 127.0.0.1:8080:80
    volumes:
      - nextcloud:/var/www/html
      - ./config:/var/www/html/config
      - ../apps:/var/www/html/apps-extra
      - /var/www/html/apps-writable
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis

  cron:
#    image: nextcloud:apache
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./config:/var/www/html/config:ro
      - ../apps:/var/www/html/apps-extra
      - /var/www/html/apps-writable
    entrypoint: /cron.sh
    depends_on:
      - app
      - db
      - redis

volumes:
  db:
  nextcloud: